apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-model-repo
  namespace: myapps
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs