apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: training-db
  name: training-db
  namespace: myapps
spec:
  replicas: 2 # Creating two PODs for our app
  selector:
    matchLabels:
      app: training-db
  template:
    metadata:
      labels:
        app: training-db
    spec:
      containers:
      - image: gcr.io/de2020/trainingdbapi:0.0.1 # Docker image name, that we pushed to GCR
        name: dbAPI     # POD name
        volumeMounts:
          - mountPath: /data/tdb
            name: training-db-vol
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
          - name: DB_LOC
            value: /data/tdb
      volumes:
        - name: training-db-vol
          persistentVolumeClaim:
            claimName: nfs-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-data
  namespace: myapps
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs